# Generated by Django 2.0.7 on 2018-07-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shcool',
            new_name='school',
        ),
    ]
