# Generated by Django 2.0.7 on 2018-07-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180720_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
