# Generated by Django 2.0.7 on 2018-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
