# Generated by Django 2.0.7 on 2018-10-26 05:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='score_apt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='scores_apt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
