# Generated by Django 2.0.7 on 2018-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180717_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(default=0),
        ),
    ]
