# Generated by Django 2.0.7 on 2018-07-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_member',
            field=models.IntegerField(default=0),
        ),
    ]
