# Generated by Django 2.0.7 on 2018-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_member',
            field=models.TextField(default=0),
        ),
    ]
