# Generated by Django 2.0.7 on 2018-09-22 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180812_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='join',
            old_name='creator',
            new_name='joiner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='apt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='apt_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_member',
            field=models.IntegerField(default=1),
        ),
    ]
